// <auto-generated />
using Cascd_Dpdwn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cascd_Dpdwn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231122042137_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Cascd_Dpdwn.Models.tbl_Country", b =>
                {
                    b.Property<int>("Cnt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cnt_id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ter_id")
                        .HasColumnType("int");

                    b.HasKey("Cnt_id");

                    b.ToTable("tbl_Country");
                });

            modelBuilder.Entity("Cascd_Dpdwn.Models.tbl_Stt", b =>
                {
                    b.Property<int>("Stt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stt_id"), 1L, 1);

                    b.Property<int>("Cnt_id")
                        .HasColumnType("int");

                    b.Property<int>("St_Name")
                        .HasColumnType("int");

                    b.HasKey("Stt_id");

                    b.ToTable("tbl_Stt");
                });

            modelBuilder.Entity("Cascd_Dpdwn.Models.tbl_Territory", b =>
                {
                    b.Property<int>("Ter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ter_id"), 1L, 1);

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tr_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ter_id");

                    b.ToTable("tbl_Territory");
                });
#pragma warning restore 612, 618
        }
    }
}
